Update values.yaml
The indentation of the external secret is wrong, because it has to be indented otherwise it wont work and will give following error if you want to install it with helm:

helm install kviklet-github-issue -n kviklet --create-namespace .    
Error: INSTALLATION FAILED: 1 error occurred:
        * Deployment.apps "kviklet-github-issue" is invalid: spec.template.spec.containers[0].envFrom[0].secretRef.name: Required value